import { z } from "zod";

/**
 * Zod schema for inserting a new job record.
 * It's based on the jobTable definition but excludes/adjusts auto-generated and relation-based fields
 * for a typical insertion payload.
 */
export const insertJobSchema = z.object({
  // Required Fields
  title: z.string().min(1, { message: "Job title is required." }).max(255),
  description: z.string().min(1, { message: "Job description is required." }),
  salary: z.number().int().positive({ message: "Salary must be a positive integer." }),
  experience: z.string().min(1, { message: "Experience level is required." }),
  location: z.string().min(1, { message: "Location is required." }),
  jobType: z.string().min(1, { message: "Job type is required." }),
  jobLevel: z.string().min(1, { message: "Job level is required." }),
  vacancy: z.number().int().positive({ message: "Vacancy must be a positive integer." }),

  // Optional/Defaulted Fields
  // 'category' has a default value 'Software' in Drizzle, so it's optional in Zod
  category: z.string().default("Software").optional(),
  
  // 'requirements' is a text array (text[]) in Drizzle, optional here for insertion
  requirements: z.array(z.string()).optional(), 
  
  // techs: z.array(z.object({ name: z.string(), years: z.string() })).optional(), // If you uncomment the techs column
  
  // Foreign Key fields (required for insertion logic, but set by the application/context, not auto-generated by DB)
  companyId: z.string().uuid({ message: "Invalid Company ID format." }),
  createdBy: z.string().uuid({ message: "Invalid Creator ID format." }),

  // Auto-generated fields (id, createdAt, updatedAt) are generally omitted for insertion
});

// Type extraction for convenience
export type InsertJobType = z.infer<typeof insertJobSchema>;